version: '1.0'

services:
  face-to-bmi:
    build:
      context: .
    ports:
      - "5006:5006"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    volumes:
      - ./static:/app/static